<<<<<<< HEAD
# Generated by Django 5.2 on 2025-07-03 06:10
=======
# Generated by Django 5.2 on 2025-07-03 16:18
>>>>>>> 5fc03de763b9693df50d47a7518f67ca9ad39af9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0005_alter_usuariopersonalizado_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='notificacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='sugerencia',
            field=models.BooleanField(default=True),
        ),
    ]
