# Generated by Django 5.2.4 on 2025-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0006_alter_usuariopersonalizado_notificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='modo_antiprocrastinacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tiempo_activado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
