# Generated by Django 5.2.4 on 2025-07-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0007_usuariopersonalizado_modo_antiprocrastinacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='urls_bloqueadas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
